### ISSUE TITLE
WollMuxBar won't start - LO 4.3.5.2 - Win7 32-bit - with workaround

### ISSUE THREAD

**Issue by winterlaite** [WollMux/WollMux#27]
Many thanks to Christoph Lutz for the workaround. PLEASE FORGIVE THE MARKDOWN-RELATED FORMATTING PROBLEMS IN THIS MESSAGE

System: Win7, 32-bit, SP1.
LO version: 4.3.5.2 (C:\Program Files\LibreOffice 4\)
WollMux version: daily build from January 16, 2015.
Install path (manual): C:\WollMux

Symptoms:
1) wollmuxbar.exe does not start the bar.
2) custom wollmuxbar.bat attempted:
(noluck-wollmuxbar.bat
@echo off
REM set JAVA_PATH="C:\ProgramData\Oracle\Java\javapath"
REM set UNO_PATH="C:\Program Files\LibreOffice 4\program"
REM set URE_HOME="C:\Program Files\LibreOffice 4\URE"
REM set PATH=%UNO_PATH%;%PATH%
java.exe -jar WollMuxBar.jar

Output of noluck-wollmuxbar.bat:

C:\WollMux>noluck-wollmuxbar.bat
com.sun.star.lib.loader.InstallationFinder::getPathFromWindowsRegistry: reading
key from Windows Registry failed: com.sun.star.lib.loader.WinRegKeyException: op
ening registry key failed!
com.sun.star.lib.loader.Loader::getCustomLoader: no UNO installation found!
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.star.lib.loader.Loader.main(Loader.java:138)
Caused by: java.lang.NoClassDefFoundError: com/sun/star/util/XStringSubstitution

        at de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar.startWollMuxBar(Woll
MuxBar.java:2434)
        at de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar.main(WollMuxBar.java
:2367)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.sun.star.util.XStringSubstituti
on
        at com.sun.star.lib.loader.Loader$CustomURLClassLoader.findClass(Loader.
java:360)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.sun.star.lib.loader.Loader$CustomURLClassLoader.loadClass(Loader.
java:371)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

C:\WollMux>

3. uno-wollmuxbar.bat:
@echo off
REM set JAVA_PATH="C:\ProgramData\Oracle\Java\javapath"
set UNO_PATH="C:\Program Files\LibreOffice 4\program"
REM set URE_HOME="C:\Program Files\LibreOffice 4\URE"
set PATH=%UNO_PATH%;%PATH%
java.exe -jar WollMuxBar.jar

Output of uno-wollmuxbar.bat:

C:\WollMux>uno-wollmuxbar.bat
com.sun.star.lib.loader.Loader::getCustomLoader: exec unoinfo: java.io.IOExcepti
on: Cannot run program ""C:\Program Files\LibreOffice 4\program"\unoinfo": Creat
eProcess error=87, The parameter is incorrect
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.star.lib.loader.Loader.main(Loader.java:138)
Caused by: java.lang.NoClassDefFoundError: com/sun/star/util/XStringSubstitution

        at de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar.startWollMuxBar(Woll
MuxBar.java:2434)
        at de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar.main(WollMuxBar.java
:2367)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.sun.star.util.XStringSubstituti
on
        at com.sun.star.lib.loader.Loader$CustomURLClassLoader.findClass(Loader.
java:360)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.sun.star.lib.loader.Loader$CustomURLClassLoader.loadClass(Loader.
java:371)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

4. Appeal to wollmux-general for help. Relevant info from thread follows:
***************
Hi Christoph, I tried replacing javaw with java in my bat file to see if there were indeed error messages. Should have done that a long time ago.
Now I _do_ get error messages.

(My WollMuxBar.bat)

set JAVA_PATH="C:\ProgramData\Oracle\Java\javapath"
set UNO_PATH="C:\Program Files\LibreOffice 4\program"
set URE_HOME="C:\Program Files\LibreOffice 4\URE"
set PATH=%URE_HOME%\bin;%UNO_PATH%;%JAVA_PATH%;%PATH%
java.exe -jar WollMuxBar.jar

(Output when running WollMuxBar.bat from console with admin privs)

C:\WollMux>java.exe -jar WollMuxBar.jar
com.sun.star.lib.loader.Loader::getCustomLoader: exec unoinfo: java.io.IOException: Cannot run program ""C:\Program Files\LibreOffice 4\program"\unoinfo": CreateProcess error=87, The parameter is incorrect
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.star.lib.loader.Loader.main(Loader.java:138)
Caused by: java.lang.NoClassDefFoundError: com/sun/star/util/XStringSubstitution at de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar.startWollMuxBar(WollMuxBar.java:2434)
        at de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar.main(WollMuxBar.java:2367)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.sun.star.util.XStringSubstitution
        at com.sun.star.lib.loader.Loader$CustomURLClassLoader.findClass(Loader.java:360)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.sun.star.lib.loader.Loader$CustomURLClassLoader.loadClass(Loader.java:371)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

_______________________________
It looks like maybe the Create Process Error=87 might be at the root of this? Or maybe missing class XStringSubstitution?
******************
5. Successful workaround given by Christoph Lutz:
*****************
HI Winter,

you are using LibreOffice 4.3.x, right? I'm still using LibreOffice 4.2.x and don't have got these problems.

Maybe they (again) changed something in the tooling-interface (here accepted argument line for "unoinfo"). You should please file an issue for that in the WollMux issuetracker https://github.com/WollMux/WollMux/issues with all the relevant infos from this thread - and we should investigate on this.

In the meantime you could try or work around the unoinfo-problem by manually providing the libreoffice location. Use the following lines (adjust your LO_PATH):

@echo off
set LO_PATH="C:\Program Files (x86)\LibreOffice 4"
java -cp WollMuxBar.jar;%LO_PATH%\URE\java\juh.jar;%LO_PATH%\program\classes\unoil.jar de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar

The difference here is that you don't use the -jar-switch in java. The -jar switch automatically uses the "tooling", while directly starteing de.muenchen.allg.itd51.wollmux.dialog.WollMuxBar doesn't require the tooling.

And of course you could also try to use LO 4.2.x...

regards,

Christoph Lutz
****
5. Remarks
It appears to me there are really two issues here.
A. As delivered, wollmuxbar.exe, will not find the UNO path for LO 4.3.5.2. This is easily worked around, but probably still an issue. Finding the UNO path does not solve the next issue.
B. As delivered (WollMux 14.12 for Windows) when wollmuxbar is started with a .bat file, will not run with "java -jar <PATH>WollMuxBar.jar. The workaround .bat file from Christoph Lutz (see above) works fine.

Question: Is it possible the "CreateProcess error=87" could be related to the (reported) Windows limit on the length of CLASSPATH?

Kind regards,
Winter

**Comment by Eymux** [comment]
Could you retest this with WollMux 16.04?

**Comment by winterlaite** [comment]
Hi, I don't have a 32-bit Windows system anymore.
As there any other thing I could do to help with that?
Regards,
Winter

**Comment by Eymux** [comment]
I'll close this for now, since we have changed the way how WollMuxBar connects to LibreOffice. If the issue pops up again, please reopen this.
